#!/bin/sh
# tools/generate-screenrc.sh
# Generate ~/.screenrc with source entries based on screen version and OS.
#
# Usage:
#   generate-screenrc.sh [options]
#
# Options:
#   --dry-run         Print what would be generated without writing.
#   --screen-ver VER  Screen major version (default: auto-detected).
#   --os-key KEY      OS key: macos, linux, or default (default: auto-detected).
#   --home-dir DIR    Home directory (default: $HOME).
#
# Environment:
#   DRY_RUN=1         Same as --dry-run.

set -eu

SCREENRC_HEADER="# Auto-generated by dotfiles install. Do not edit."

dry_run=0
screen_ver=""
os_key=""
home_dir="${HOME}"

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)
            dry_run=1
            shift
            ;;
        --screen-ver)
            screen_ver="$2"
            shift 2
            ;;
        --os-key)
            os_key="$2"
            shift 2
            ;;
        --home-dir)
            home_dir="$2"
            shift 2
            ;;
        *)
            printf "Unknown option: %s\n" "$1" >&2
            exit 1
            ;;
    esac
done

if [ "${DRY_RUN:-0}" = "1" ]; then
    dry_run=1
fi

if [ -z "$screen_ver" ]; then
    screen_ver=$(screen --version 2>/dev/null \
        | sed -nE 's/^Screen( version)? ([0-9]+)\..*/\2/p')
    screen_ver="${screen_ver:-4}"
fi

if [ -z "$os_key" ]; then
    _os=$(uname -s)
    case "$_os" in
        Darwin) os_key=macos  ;;
        Linux)  os_key=linux  ;;
        *)      os_key=default ;;
    esac
fi

print_source_entries() {
    printf "  source ~/.config/screen/common.screenrc\n"
    printf "  source ~/.config/screen/v%s/base.screenrc\n" "$screen_ver"
    printf "  source ~/.config/screen/v%s/statusline-%s.screenrc\n" \
        "$screen_ver" "$os_key"
    printf "  source ~/.config/screen/host.screenrc\n"
    for _manual in "${home_dir}/.config/screen/"*.screenrc; do
        [ -e "$_manual" ] || continue
        _manual_name="${_manual##*/}"
        case "$_manual_name" in common.screenrc|host.screenrc) continue ;; esac
        if [ ! -L "$_manual" ]; then
            printf "  source ~/.config/screen/%s\n" "$_manual_name"
        fi
    done
}

if [ "$dry_run" = "1" ]; then
    printf "Generate: ~/.screenrc with source entries:\n"
    print_source_entries
    exit 0
fi

{
    printf "%s\n" "$SCREENRC_HEADER"
    printf "# Generated for: screen %s.x, %s\n" "$screen_ver" "$os_key"
    printf "source ~/.config/screen/common.screenrc\n"
    printf "source ~/.config/screen/v%s/base.screenrc\n" "$screen_ver"
    printf "source ~/.config/screen/v%s/statusline-%s.screenrc\n" \
        "$screen_ver" "$os_key"
    printf "source ~/.config/screen/host.screenrc\n"
    for _manual in "${home_dir}/.config/screen/"*.screenrc; do
        [ -e "$_manual" ] || continue
        _manual_name="${_manual##*/}"
        case "$_manual_name" in common.screenrc|host.screenrc) continue ;; esac
        if [ ! -L "$_manual" ]; then
            printf "source ~/.config/screen/%s\n" "$_manual_name"
        fi
    done
} > "${home_dir}/.screenrc"

printf "Generated: ~/.screenrc with source entries:\n"
print_source_entries
